FROM jupyter/pyspark-notebook

# Set the working directory
WORKDIR /app
# Install Python dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the training script and data files
COPY train.py /app/train.py

COPY . /app/

RUN  mkdir -p model  temp
RUN chmod -R 777 model  temp
# Set the entrypoint to run the training script
EXPOSE 4040

ENTRYPOINT ["python", "train.py"]
